config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :employees
  devise_for :users
  root "dashboard#index"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_enumeration_for :state, with: State

	validates :name, :cpf, :birth_date, :phone,  presence: :true

	def address
		
	end

	def phones
		
	end

	def to_s
		name	
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
validates :name, :birth_date, :gender, presence: :true

	def to_s
		name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :timeoutable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  responders :flash

  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :define_layout
private

	def message
		@message ||= {}
	end

	helper_method :message

	def define_environment_message
		message[:alert] ||= []
	end

	def define_layout
	    if user_signed_in?
	    else
	      'login'
	    end 
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @employees = Employee.all
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
    @employee.birth_date = @employee.birth_date.strftime("%d/%m/%Y")  unless @employee.birth_date.nil?
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with @employee, :location => employees_path
  end

  def update
    @employee.update(employee_params)
    respond_with @employee, :location => employees_path
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :cpf, :phone, :email, :birth_date, :street, :number_street, :neighborhood, :city, :state, :zip_code, :teacher)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @students = Student.all
    respond_with(@students)
  end

  def show
    respond_with(@student)
  end

  def new
    @student = Student.new
    respond_with(@student)
  end

  def edit
    @student.birth_date = @student.birth_date.strftime("%d/%m/%Y")  unless @student.birth_date.nil?
  end

  def create
    @student = Student.new(student_params)
    @student.save
    respond_with @student, :location => students_path
  end

  def update
    @student.update(student_params)
    respond_with @student, :location => students_path
  end

  def destroy
    @student.destroy
    respond_with(@student)
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :birth_date, :cpf, :gender, :profession, :phone, :cel_phone, :father, :mother, :responsible, :cpf_responsible, :street, :number_street, :zip_code, :neighborhood, :city, :state, :rg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/employees/_address.html.erb
<br>
<div class="row">
	<div class="col-md-5">
		<%= f.input :street %>
	</div>
	<div class="col-md-2">	
		<%= f.input :number_street %>
	</div>
	<div class="col-md-3">	
		<%= f.input :neighborhood %>
	</div>
</div>

<div class="row">
	<div class="col-md-5">
		<%= f.input :city %>
	</div>
	<div class="col-md-2">	
		<%= f.input :zip_code %>
	</div>
	<div class="col-md-1">	
		<%= f.input :state, collection: State.to_a %>
	</div>
</div>

app/views/employees/_form.html.erb
<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :name %>

    <%= f.input :cpf %>

    <%= f.input :phone %>

    <%= f.input :email %>

    <%= f.input  :birth_date %> 

    <%= f.input :street %>

    <%= f.input :number_street %>

    <%= f.input :neighborhood %>

    <%= f.input :city %>

    <%= f.input :state, collection: State %>

    <%= f.input :zip_code %>



  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/_main.html.erb
<br>
   <div class="row">
		<div class="col-md-5">
			<%= f.input :name, input_html: {maxlength: 50}%>
		</div>
	</div>

   <div class="row">
		<div class="col-md-2">
			<%= f.input :birth_date,  as: :string, input_html: {data: {provide:'datepicker' },class: 'date'}%>
		</div>
	</div>

   <div class="row">
		<div class="col-md-5">
			<%= f.input :cpf, input_html: {class: 'cpf'}%>
		</div>
		<div class="col-md-1">
			<%= f.input :teacher%>
		</div>
	</div>
   <div class="row">
   		<div class="col-md-5">
			<%= f.input :email%>
		</div>
		 		<div class="col-md-3">
			<%= f.input :phone, input_html: {class: 'phone'}%>
		</div>
   </div>

app/views/employees/edit.html.erb
<h3>Editar Funcionário</h3>

<%= render 'form' %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Birth date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.cpf %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.email %></td>
        <td><%= employee.birth_date %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h3>Novo Funcionário</h3>
<%= render 'form' %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @employee.cpf %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @employee.birth_date %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/_content_block.html.erb
<%= render 'layouts/navegation_bar' %>
<%= render 'layouts/messages' %>
<div class"container">
	<div class="row">
		<div class="col-md-4">
			   <%= image_tag  "/images/login1.jpg", :width => 200 %>
     
		</div>
		<div class="col-md-3">
			<%= yield %>
		</div>
		<div class="col-md-4">
		</div>
	</div>
</div>

app/views/layouts/_menu.html.erb
<div class="btn-group" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Studio
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><%= link_to "Funcionários", employees_path%></li>
      <li><%= link_to 'Alunos', students_path %></li>
      <li><a href="#">Cursos</a></li>
      <li><a href="#">Pacotes</a></li>
      <li><a href="#">Turmas</a></li>
      <li><a href="#">Espetaculos</a></li>
    </ul>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Turmas
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Enturmação</a></li>
      <li><a href="#">Presença</a></li>
    </ul>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Financeiro
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Contratos</a></li>
      <li><a href="#">Contas à receber</a></li>
      <li><a href="#">Contas à pagar</a></li>
    </ul>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container-fluid" id="messages-content">
  <% { :message => false, :flash => true }.each do |method, can_close| %>
    <% { :alert => :danger, :warning => :warning, :notice => :success, :info => :info }.each do |type, css| %>
      <% messages = [send(method)[type]].flatten.reject &:blank? -%>
      <% messages.each do |message| -%>
        <% next if message.blank? -%>
        <div class="row-fluid">
          <div class="alert alert-<%= css %>">
            <% if can_close -%><a href="#" class="close" data-dismiss="alert">&times;</a><% end -%>
            <%= message %>
          </div>
        </div>
      <% end -%>
    <% end -%>
  <% end -%>
</div>

app/views/layouts/_navegation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Studio de Dança Priscila Nayara</a>
    </div>
    <% if user_signed_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Editar</a></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to " Logof", destroy_user_session_path, method: :delete, data: { confirm: 'Deseja Realmente sair do sistema?' }, :class => "glyphicon glyphicon-off" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <% end %>
    <!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <csrf_meta_tags charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Striped</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/navegation_bar' %>
    <%= render 'layouts/menu'%>
    <br><br>
    <%= render 'layouts/messages' %>
    <div class="row">
      <div class="col-md-1">
        <%= image_tag  "/images/login1.jpg", :width => 200 %>
      </div>
      <div class="col-md-10">
        <div class="jumbotron">
          <div class="container">
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
<html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <csrf_meta_tags charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Striped</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span6 offset3">
          <%= render "layouts/content_block" %>
        </div>
      </div>
      <hr>
    </div>


    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/students/_address.html.erb
<br>
<div class="row">
	<div class="col-md-5">
		<%= f.input :street %>
	</div>
	<div class="col-md-2">	
		<%= f.input :number_street %>
	</div>
	<div class="col-md-3">	
		<%= f.input :neighborhood %>
	</div>
</div>

<div class="row">
	<div class="col-md-5">
		<%= f.input :city %>
	</div>
	<div class="col-md-2">	
		<%= f.input :zip_code %>
	</div>
	<div class="col-md-1">	
		<%= f.input :state, collection: State.to_a %>
	</div>
</div>

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>

  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"> <%= link_to "Geral", "#main", :"data-toggle" => :tab %></li>
      <li> <%= link_to "Endereço", "#address", :"data-toggle" => :tab %></li>
    </ul>
  </div>
 <div class="tab-content">
    <div class="tab-pane fade active in" id="main">
      <%= render "main", :f => f %>
    </div>
    <div class="tab-pane" id="address">
      <%= render "address", :f => f %>
    </div>
 </div>
 
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to "Voltar", students_path, class: "btn btn-info"%>
  </div>
<% end %>

app/views/students/_main.html.erb
<br>
   <div class="row">
		<div class="col-md-5">
			<%= f.input :name, input_html: {maxlength: 50}%>
		</div>
	</div>

   <div class="row">
		<div class="col-md-2">
			<%= f.input :birth_date,  as: :string, input_html: {data: {provide:'datepicker' },class: 'date'}%>
		</div>
		<div class="col-md-4">
			<%= f.input :profession, input_html: {maxlength: 50}%>
		</div>
		<div class="col-md-4">
			<%= f.input :gender, collection: Gender.to_a %>
		</div>
	</div>

   <div class="row">
		<div class="col-md-4">
			<%= f.input :cpf, input_html: {class: 'cpf'}%>
		</div>
		<div class="col-md-4">
			<%= f.input :rg, input_html: {class: ''}%>
		</div>
		<div class="col-md-1">
		</div>
	</div>
   <div class="row">
   		<div class="col-md-3">
			<%= f.input :cel_phone, input_html: {class: 'phone'}%>
		</div>
		 		<div class="col-md-3">
			<%= f.input :phone, input_html: {class: 'phone'}%>
		</div>
   </div>
   <fieldset>
   	<legend>Filiação</legend>
   		<div class="row">
   			<div class="col-md-5">
				<%= f.input :mother, input_html: {maxlength: 50}%>
   			</div>
   			<div class="col-md-5">
				<%= f.input :father, input_html: {maxlength: 50}%>
   			</div>
   		</div>
   		<div class="row">
   			<div class="col-md-5">
				<%= f.input :responsible, input_html: {maxlength: 50}%>
   			</div>
   			<div class="col-md-4">
				<%= f.input :cpf_responsible, input_html: {class: "cpf"}%>
   			</div>
   		</div>
   </fieldset>

app/views/students/edit.html.erb
<h3>Editar Aluno</h3>
<%= render 'form' %>

app/views/students/index.html.erb
<table class="table">
  <td>
    <h3>Listagem de Alunos</h3>
  </td>
  <td width='5%'>
    <%= link_to new_student_path, role: 'button' do %>
      <h2 class="text-success" title='Novo Aluno'><span class="glyphicon glyphicon-plus"></span></h2>
    <% end %>    
  </td>
</table>

<div class="input-group">
  <span class="input-group-addon" id="sizing-addon2"><span class="glyphicon glyphicon-search"></span></span>
  <%= text_field_tag 'txtBusca', '', :class => 'form-control input-search', :id => 'txtBusca',:placeholder => "Buscar nesta lista", :alt =>"list" %>
</div>

<table class=" list table table-striped table-bordered">
<tr>
  <th>
    Nome
  </th>
  <th width="5%">
  </th>
</tr>
  <% if @students.any?%>
    <% @students.each do |e|%>
      <tr>
        <td>
          <%= e%>
        </td>
        <td>
          <%= link_to '', edit_student_path(e), class: "glyphicon glyphicon-pencil" %>
          <%= link_to '', e, method: :delete, data:{confirm: 'Confirma exclusão ?'}, class: "glyphicon glyphicon-trash text-danger" %>
        </td>
      </tr>
    <% end %>
  <%else%>
    <tr>
      <td colspan="3" align="center">
        Nenhum registro foi encontrado.
      </td>
    </tr>
  <%end%>
</table>

app/views/students/new.html.erb
<h3>Novo Aluno</h3>
<%= render 'form' %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @student.birth_date %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @student.cpf %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.gender %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @student.profession %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Cel phone:</strong>
  <%= @student.cel_phone %>
</p>

<p>
  <strong>Father:</strong>
  <%= @student.father %>
</p>

<p>
  <strong>Mother:</strong>
  <%= @student.mother %>
</p>

<p>
  <strong>Responsible:</strong>
  <%= @student.responsible %>
</p>

<p>
  <strong>Cpf responsible:</strong>
  <%= @student.cpf_responsible %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>